version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: test
        MYSQL_PASSWORD: test
    ports:
        - "3306:3306"
    volumes:
        - ./database:/var/lib/mysql
  php:
    build:
      context: docker
      dockerfile: Dockerfile.php
    container_name: php
    volumes:
        - ./src:/var/www/html
    ports:
        - "80:80"
    depends_on:
        - db
    environment:
        - MYSQL_HOST=db
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
        - MYSQL_DATABASE=app
        - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_USER: root
        PMA_PASSWORD: root
    ports:
        - "8080:80"
    depends_on:
        - db